project:
  type: book

book:
  title: "Fragile Forms Collection"
  author: "ART ME UP by MELP"
  cover-image: cover.jpg
  chapters:
    - index.qmd
    - still.qmd

format:
  pdf:
    documentclass: scrbook
    papersize: a4
    fontsize: 11pt

    geometry:
      - inner=25mm
      - outer=20mm
      - top=22mm
      - bottom=25mm

    mainfont: "Helvetica Neue"
